"use client";

import './globals.css';

import { Inter } from 'next/font/google';
import {
  configureChains,
  createConfig,
  WagmiConfig,
} from 'wagmi';
import { MetaMaskConnector } from 'wagmi/connectors/metaMask';
import { publicProvider } from 'wagmi/providers/public';

import Navbar from '@/components/Navbar';
import { bscTestnet } from '@wagmi/chains';

"use-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const { chains, publicClient, webSocketPublicClient } = configureChains([bscTestnet], [publicProvider()]);

const config = createConfig({
	autoConnect: true,
	publicClient,
	webSocketPublicClient,
	connectors: [new MetaMaskConnector({chains})],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<WagmiConfig config={config}>
					<main className=" flex min-h-screen flex-col">
					<Navbar />
					{children}
					</main>
				</WagmiConfig>
			</body>
		</html>
	);
}
